# Generated by Django 5.2.1 on 2025-05-21 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='tickets_number',
            new_name='spectator_number',
        ),
    ]
