# Generated by Django 5.2.1 on 2025-05-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_rename_tickets_number_offer_spectator_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
