# Generated by Django 5.2.1 on 2025-05-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='generated_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
