# Generated by Django 5.2 on 2025-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0007_remove_cart_ordered_remove_cart_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
