# Generated by Django 5.2.1 on 2025-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0008_cart_ordered_cart_ordered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
