# Generated by Django 5.2 on 2025-05-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='a9fcceb1ade70265dbfc71fe9adb882d', max_length=255),
        ),
    ]
