# Generated by Django 5.2 on 2025-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_managers_remove_customer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='29c4e0c65e9073576d1b16e40a22310a', max_length=255),
        ),
    ]
