# Generated by Django 5.2 on 2025-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='6f0fbd36a4a6d9916e7590ed6f711ac1', max_length=255),
        ),
    ]
