# Generated by Django 5.2 on 2025-05-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='399ba776d83cbdefe1b6d5b59606f08e', max_length=255),
        ),
    ]
