# Generated by Django 5.2 on 2025-05-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='33ad1b83c1df23735da5aa55c1d292d3', max_length=255),
        ),
    ]
