# Generated by Django 5.2.1 on 2025-05-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='91ab53c40131aae3604255c0ed7dca32', max_length=255),
        ),
    ]
