# Generated by Django 5.2.1 on 2025-05-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customer_generated_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generated_key',
            field=models.CharField(default='9c57e4f61ac7420b1ed8556127de9505', max_length=255),
        ),
    ]
